### ISSUE TITLE
FMS API Returning Bad Websites

### ISSUE THREAD

**Issue by phil-lopreiato** [the-blue-alliance/the-blue-alliance#1311]
For every team in FMSAPI, it's returning "Coming Soon" as the value for the website, which of course, breaks it. See http://www.thebluealliance.com/team/503

We should update the parser to have "Coming Soon" mean `None` so we can not overwrite further data.

**Comment by fangeugene** [comment]
... Why do they do this?

**Comment by synth3tk** [comment]
No clue. If you don't have a website, there's no reason to put anything in the field.

On FIRST's side, though, they should be validating it. Again, no reason to allow non-URL input.

**Comment by fangeugene** [comment]
The problem isn't the teams. It's FIRST. They replaced every URL with
"coming soon".

**Comment by synth3tk** [comment]
That's odd. When I look at the API used on the website, it either shows the team's URL, or that key/value pair doesn't get returned.

**Comment by fangeugene** [comment]
Website api =/= FRC API

**Comment by fangeugene** [comment]
I think FIRST fixed it. Can someone else confirm?

**Comment by synth3tk** [comment]
Gotcha. I assumed they were one and the same. Looks like we still have nearly all the [new teams](http://www.thebluealliance.com/team/6214) with "Coming Soon", but 503 went back to normal, so whatever caused it to happen everywhere is fixed.

We'll still need that parser update. Is there a way for someone to get in contact with them and figure out if they'll be sticking with that?

**Comment by phil-lopreiato** [comment]
@fangeugene still isn't fixed for me. I just hit the API for a few teams and it's still not fixed yet...

```
{
  "teams": [
    {
      "teamNumber": 1124,
      "nameFull": "Avon Public Schools/UTC/OFS & Avon High School",
      "nameShort": "UberBots",
      "city": "Avon",
      "stateProv": "Connecticut",
      "country": "USA",
      "website": "Coming Soon",
      "rookieYear": 2003,
      "robotName": "Orion ",
      "districtCode": "NE"
    }
  ],
  "teamCountTotal": 1,
  "teamCountPage": 1,
  "pageCurrent": 1,
  "pageTotal": 1
}
```

**Comment by phil-lopreiato** [comment]
Bug report got closed, everything now returns `http://www.firstinspires.org` as the website. That's better, but still not ideal. Is this good enough for now, or should make a change on TBA-side?

**Comment by fangeugene** [comment]
Can we get FIRST to return null?

**Comment by phil-lopreiato** [comment]
Fixed by https://github.com/the-blue-alliance/the-blue-alliance/commit/c900b429cea37abc00675573b50bcd54d6f088d2
