### ISSUE TITLE
Issues bootstrapping data in dev environment

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#2037]
## Expected Behavior
The documentation should provide full instructions to set up development environment.

## Current Behavior
`paver bootstrap` exits with an error. The documentation does not address how to fix this error ( https://github.com/the-blue-alliance/the-blue-alliance/blob/master/docs/dev-container.md#bootstrapping-data ).

```
root@tba-docker:/tba# paver bootstrap
---> pavement.bootstrap
Running python bootstrap.py --url localhost:41017 2016necmp
Configuring GAE Remote API on localhost:41017 to import 2016necmp
Traceback (most recent call last):
  File "bootstrap.py", line 247, in <module>
    main(args.key, args.url)
  File "bootstrap.py", line 214, in main
    remote_api_stub.ConfigureRemoteApi(None, '/_ah/remote_api', local_auth_func, url)
  File "/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 881, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 586, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "/google_appengine/google/appengine/tools/appengine_rpc.py", line 393, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>
```

## Possible Solution
This may be caused because my APIv3 key is misconfigured, but I am not sure.

## Steps to Reproduce (for bugs)
1. Set up new docker dev environment
2. `paver bootstrap`

## Context
Not able to bootstrap my dev instance

## Your Environment
* Version used: 
* Operating System and version (desktop or mobile): Mac OS High Sierra, although this issue occurs inside of the docker.

**Comment by phil-lopreiato** [comment]
Interesting, I just tried this on a fresh container and everything worked. Can you recreate the container `vagrant reload` to make sure the changes sync (specifically 0cfa218c477ff479f7b26c99c1325cb25f9f3a3f)

**Comment by gregmarra** [comment]
Same error after reloading.

`vagrant reload` =>
```
alliance git:(master) ✗ vagrant reload
==> default: Stopping container...
==> default: Deleting the container...
==> default: Building the container from a Dockerfile...
    default: Sending build context to Docker daemon   7.68kB
    default: Step 1/20 : FROM ubuntu:16.04
    default:  ---> 20c44cd7596f
    default: Step 2/20 : MAINTAINER The Blue Alliance
    default:  ---> Using cache
    default:  ---> 525e94ec72f9
    default: Step 3/20 : RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    default:  ---> Using cache
    default:  ---> df71a8a9b8af
    default: Step 4/20 : RUN apt-get update && apt-get install -y   git   wget   unzip   sudo   python2.7   python2.7-dev   python-pip   build-essential   checkinstall   libssl-dev   tmux   vim   openssh-server
    default:  ---> Using cache
    default:  ---> 11ab49eb161a
    default: Step 5/20 : RUN mkdir /var/run/sshd
    default:  ---> Using cache
    default:  ---> 31e74d3ae787
    default: Step 6/20 : RUN echo 'root:tba' | chpasswd
    default:  ---> Using cache
    default:  ---> 0e9463527424
    default: Step 7/20 : RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    default:  ---> Using cache
    default:  ---> baea35483413
    default: Step 8/20 : RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
    default:  ---> Using cache
    default:  ---> 6f3444dfe4ab
    default: Step 9/20 : ENV NOTVISIBLE "in users profile"
    default:  ---> Using cache
    default:  ---> 94636877a8b4
    default: Step 10/20 : RUN echo "export VISIBLE=now" >> /etc/profile
    default:  ---> Using cache
    default:  ---> 4862d1b1deca
    default: Step 11/20 : EXPOSE 22
    default:  ---> Using cache
    default:  ---> b44f951c59e9
    default: Step 12/20 : ENV GAE_VERSION 1.9.61
    default:  ---> Using cache
    default:  ---> 126971aad49f
    default: Step 13/20 : RUN wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$GAE_VERSION.zip -nv
    default:  ---> Using cache
    default:  ---> 40df15c304aa
    default: Step 14/20 : RUN unzip -q google_appengine_$GAE_VERSION.zip
    default:  ---> Using cache
    default:  ---> 6a604fba3ef0
    default: Step 15/20 : ENV NVM_DIR /nvm
    default:  ---> Using cache
    default:  ---> bcf27d5a668d
    default: Step 16/20 : ENV NODE_VERSION 8.0.0
    default:  ---> Using cache
    default:  ---> d9f17c805699
    default: Step 17/20 : RUN wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash     && . $NVM_DIR/nvm.sh     && nvm install $NODE_VERSION --silent     && nvm alias default $NODE_VERSION     && nvm use default --silent
    default:  ---> Using cache
    default:  ---> 42597b2db683
    default: Step 18/20 : EXPOSE 8000
    default:  ---> Using cache
    default:  ---> 36cb12c9735e
    default: Step 19/20 : EXPOSE 8080-8089
    default:  ---> Using cache
    default:  ---> 88a0731dd609
    default: Step 20/20 : CMD /usr/sbin/sshd -D
    default:  ---> Using cache
    default:  ---> 35046abc6e30
    default: Successfully built 35046abc6e30
    default: 
    default: Image: 35046abc6e30
==> default: Creating the container...
    default:   Name: tba
    default:  Image: 35046abc6e30
    default: Volume: /Users/gregmarra/codez/the-blue-alliance:/vagrant
    default:   Port: 8080:8080
    default:   Port: 8081:8081
    default:   Port: 8082:8082
    default:   Port: 8083:8083
    default:   Port: 8084:8084
    default:   Port: 8085:8085
    default:   Port: 8086:8086
    default:   Port: 8087:8087
    default:   Port: 8088:8088
    default:   Port: 8089:8089
    default:   Port: 8000:8000
    default:   Port: 127.0.0.1:2222:22
    default:  
    default: Container created: 0ebfae2be699d294
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: root
    default: SSH auth method: password
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Rsyncing folder: /Users/gregmarra/codez/the-blue-alliance/ => /tba
==> default:   - Exclude: [".vagrant/", ".git/", "node_modules/", "lib/", "static/compiled/"]
==> default: Running provisioner: shell...
    default: Running: inline script
    default: /nvm/versions/node/v8.0.0/bin/uglifyjs -> /nvm/versions/node/v8.0.0/lib/node_modules/uglify-js/bin/uglifyjs
    default: added 18 packages in 1.865s
    default: /nvm/versions/node/v8.0.0/bin/uglifycss -> /nvm/versions/node/v8.0.0/lib/node_modules/uglifycss/uglifycss
    default: /nvm/versions/node/v8.0.0/bin/uglifyjs -> /nvm/versions/node/v8.0.0/lib/node_modules/uglify-es/bin/uglifyjs
    default: /nvm/versions/node/v8.0.0/bin/lessc -> /nvm/versions/node/v8.0.0/lib/node_modules/less/bin/lessc
    default: /nvm/versions/node/v8.0.0/bin/gulp -> /nvm/versions/node/v8.0.0/lib/node_modules/gulp-cli/bin/gulp.js
    default: added 261 packages in 11.537s
    default: Collecting pip
    default:   Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    default: Installing collected packages: pip
    default:   Found existing installation: pip 8.1.1
    default:     Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
    default: Successfully installed pip-9.0.1
    default: Collecting jinja2==2.6 (from -r requirements.txt (line 3))
    default:   Downloading Jinja2-2.6.tar.gz (389kB)
    default: Collecting numpy==1.6.1 (from -r requirements.txt (line 4))
    default:   Downloading numpy-1.6.1-cp27-cp27mu-manylinux1_x86_64.whl (13.6MB)
    default: Collecting Paver==1.2.4 (from -r requirements.txt (line 5))
    default:   Downloading Paver-1.2.4-py2.py3-none-any.whl (295kB)
    default: Collecting pep8==1.7.0 (from -r requirements.txt (line 6))
    default:   Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
    default: Collecting pyyaml (from -r requirements.txt (line 7))
    default:   Downloading PyYAML-3.12.tar.gz (253kB)
    default: Building wheels for collected packages: jinja2, pyyaml
    default:   Running setup.py bdist_wheel for jinja2: started
    default:   Running setup.py bdist_wheel for jinja2: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/58/3f/84/23e0402d462dfe2b764ec9e200c84ecbbe6094bc3df4d2a70f
    default:   Running setup.py bdist_wheel for pyyaml: started
    default:   Running setup.py bdist_wheel for pyyaml: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
    default: Successfully built jinja2 pyyaml
    default: Installing collected packages: jinja2, numpy, Paver, pep8, pyyaml
    default: Successfully installed Paver-1.2.4 jinja2-2.6 numpy-1.6.1 pep8-1.7.0 pyyaml-3.12
    default: Collecting Django==1.4.3 (from -r travis_requirements.txt (line 2))
    default:   Downloading Django-1.4.3.tar.gz (7.7MB)
    default: Collecting Paver==1.1.1 (from -r travis_requirements.txt (line 3))
    default:   Downloading Paver-1.1.1.tar.gz (304kB)
    default: Collecting WebTest==2.0.28 (from -r travis_requirements.txt (line 4))
    default:   Downloading WebTest-2.0.28-py2.py3-none-any.whl
    default: Collecting unittest2==0.5.1 (from -r travis_requirements.txt (line 5))
    default:   Downloading unittest2-0.5.1.zip (78kB)
    default: Collecting webapp2==2.5.2 (from -r travis_requirements.txt (line 6))
    default:   Downloading webapp2-2.5.2.zip (243kB)
    default: Requirement already up-to-date: jinja2==2.6 in /usr/local/lib/python2.7/dist-packages (from -r travis_requirements.txt (line 7))
    default: Collecting appengine-fixture-loader==0.1.8 (from -r travis_requirements.txt (line 8))
    default:   Downloading Appengine-Fixture-Loader-0.1.8.tar.gz
    default: Collecting pytz==2016.4 (from -r travis_requirements.txt (line 9))
    default:   Downloading pytz-2016.4-py2.py3-none-any.whl (480kB)
    default: Requirement already up-to-date: PyYAML==3.12 in /usr/local/lib/python2.7/dist-packages (from -r travis_requirements.txt (line 10))
    default: Requirement already up-to-date: pep8==1.7.0 in /usr/local/lib/python2.7/dist-packages (from -r travis_requirements.txt (line 11))
    default: Collecting requests[security] (from -r travis_requirements.txt (line 12))
    default:   Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    default: Collecting pyOpenSSL (from -r travis_requirements.txt (line 13))
    default:   Downloading pyOpenSSL-17.4.0-py2.py3-none-any.whl (52kB)
    default: Collecting ndg-httpsclient (from -r travis_requirements.txt (line 14))
    default:   Downloading ndg_httpsclient-0.4.3-py2-none-any.whl
    default: Collecting pyasn1 (from -r travis_requirements.txt (line 15))
    default:   Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    default: Collecting WebOb>=1.2 (from WebTest==2.0.28->-r travis_requirements.txt (line 4))
    default:   Downloading WebOb-1.7.4-py2.py3-none-any.whl (84kB)
    default: Collecting beautifulsoup4 (from WebTest==2.0.28->-r travis_requirements.txt (line 4))
    default:   Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
    default: Collecting waitress>=0.8.5 (from WebTest==2.0.28->-r travis_requirements.txt (line 4))
    default:   Downloading waitress-1.1.0-py2.py3-none-any.whl (114kB)
    default: Collecting six (from WebTest==2.0.28->-r travis_requirements.txt (line 4))
    default:   Downloading six-1.11.0-py2.py3-none-any.whl
    default: Collecting urllib3<1.23,>=1.21.1 (from requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    default: Collecting idna<2.7,>=2.5 (from requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    default: Collecting chardet<3.1.0,>=3.0.2 (from requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    default: Collecting certifi>=2017.4.17 (from requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading certifi-2017.11.5-py2.py3-none-any.whl (330kB)
    default: Collecting cryptography>=1.3.4; extra == "security" (from requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading cryptography-2.1.3-cp27-cp27mu-manylinux1_x86_64.whl (2.2MB)
    default: Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.3.4; extra == "security"->requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl (405kB)
    default: Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading enum34-1.1.6-py2-none-any.whl
    default: Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "security"->requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading asn1crypto-0.23.0-py2.py3-none-any.whl (99kB)
    default: Collecting ipaddress; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading ipaddress-1.0.18-py2-none-any.whl
    default: Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security]->-r travis_requirements.txt (line 12))
    default:   Downloading pycparser-2.18.tar.gz (245kB)
    default: Building wheels for collected packages: Django, Paver, unittest2, webapp2, appengine-fixture-loader, pycparser
    default:   Running setup.py bdist_wheel for Django: started
    default:   Running setup.py bdist_wheel for Django: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/59/1f/ca/2703b57237417aea40e977ec24c5d3bfaf66780d7a492fd7ab
    default:   Running setup.py bdist_wheel for Paver: started
    default:   Running setup.py bdist_wheel for Paver: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/88/fa/ec/5e7649000a23f0c5521e8e72bac9969b5a1cf122e1f940809e
    default:   Running setup.py bdist_wheel for unittest2: started
    default:   Running setup.py bdist_wheel for unittest2: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/ad/08/5b/1b3f476b0a285ae7a87b81b112e79824d8c9ea98f81e98f743
    default:   Running setup.py bdist_wheel for webapp2: started
    default:   Running setup.py bdist_wheel for webapp2: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/3c/4a/1b/c9d256ac423e889b2d647c6d58ba8cc87d700b3225856feb02
    default:   Running setup.py bdist_wheel for appengine-fixture-loader: started
    default:   Running setup.py bdist_wheel for appengine-fixture-loader: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/7a/e8/37/ddd0161ea2b2be6aad63fc101918e4ae3a5aecb3c3c08b8338
    default:   Running setup.py bdist_wheel for pycparser: started
    default:   Running setup.py bdist_wheel for pycparser: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/95/14/9a/5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
    default: Successfully built Django Paver unittest2 webapp2 appengine-fixture-loader pycparser
    default: Installing collected packages: Django, Paver, WebOb, beautifulsoup4, waitress, six, WebTest, unittest2, webapp2, appengine-fixture-loader, pytz, urllib3, idna, chardet, certifi, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, requests, pyasn1, ndg-httpsclient
    default:   Found existing installation: Paver 1.2.4
    default:     Uninstalling Paver-1.2.4:
    default:       Successfully uninstalled Paver-1.2.4
    default: Successfully installed Django-1.4.3 Paver-1.1.1 WebOb-1.7.4 WebTest-2.0.28 appengine-fixture-loader-0.1.8 asn1crypto-0.23.0 beautifulsoup4-4.6.0 certifi-2017.11.5 cffi-1.11.2 chardet-3.0.4 cryptography-2.1.3 enum34-1.1.6 idna-2.6 ipaddress-1.0.18 ndg-httpsclient-0.4.3 pyOpenSSL-17.4.0 pyasn1-0.4.2 pycparser-2.18 pytz-2016.4 requests-2.18.4 six-1.11.0 unittest2-0.5.1 urllib3-1.22 waitress-1.1.0 webapp2-2.5.2
    default: ---> pavement.install_libs
    default: pip install -r deploy_requirements.txt -t lib
    default: Collecting iso8601==0.1.11 (from -r deploy_requirements.txt (line 3))
    default:   Downloading iso8601-0.1.11-py2.py3-none-any.whl
    default: Collecting google-api-python-client==1.6.2 (from -r deploy_requirements.txt (line 4))
    default:   Downloading google_api_python_client-1.6.2-py2.py3-none-any.whl (52kB)
    default: Collecting google-cloud-bigquery==0.25.0 (from -r deploy_requirements.txt (line 5))
    default:   Downloading google_cloud_bigquery-0.25.0-py2.py3-none-any.whl (41kB)
    default: Collecting beautifulsoup4 (from -r deploy_requirements.txt (line 6))
    default:   Using cached beautifulsoup4-4.6.0-py2-none-any.whl
    default: Collecting GoogleAppEngineCloudStorageClient (from -r deploy_requirements.txt (line 7))
    default:   Downloading GoogleAppEngineCloudStorageClient-1.9.22.1.tar.gz
    default: Collecting six<2dev,>=1.6.1 (from google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Using cached six-1.11.0-py2.py3-none-any.whl
    default: Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Downloading uritemplate-3.0.0-py2.py3-none-any.whl
    default: Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Downloading oauth2client-4.1.2-py2.py3-none-any.whl (99kB)
    default: Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Downloading httplib2-0.10.3.tar.gz (204kB)
    default: Collecting google-cloud-core<0.26dev,>=0.25.0 (from google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading google_cloud_core-0.25.0-py2.py3-none-any.whl (52kB)
    default: Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    default: Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    default: Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.2->-r deploy_requirements.txt (line 4))
    default:   Using cached pyasn1-0.4.2-py2.py3-none-any.whl
    default: Collecting google-auth<2.0.0dev,>=0.4.0 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading google_auth-1.2.1-py2.py3-none-any.whl (61kB)
    default: Collecting protobuf>=3.0.0 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading protobuf-3.5.0.post1-py2.py3-none-any.whl (389kB)
    default: Collecting google-auth-httplib2 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading google_auth_httplib2-0.0.3-py2.py3-none-any.whl
    default: Collecting googleapis-common-protos>=1.3.4 (from google-cloud-core<0.26dev,>=0.25.0->google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading googleapis-common-protos-1.5.3.tar.gz
    default: Collecting cachetools>=2.0.0 (from google-auth<2.0.0dev,>=0.4.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading cachetools-2.0.1-py2.py3-none-any.whl
    default: Collecting setuptools (from protobuf>=3.0.0->google-cloud-core<0.26dev,>=0.25.0->google-cloud-bigquery==0.25.0->-r deploy_requirements.txt (line 5))
    default:   Downloading setuptools-38.2.0-py2.py3-none-any.whl (489kB)
    default: Building wheels for collected packages: GoogleAppEngineCloudStorageClient, httplib2, googleapis-common-protos
    default:   Running setup.py bdist_wheel for GoogleAppEngineCloudStorageClient: started
    default:   Running setup.py bdist_wheel for GoogleAppEngineCloudStorageClient: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/c7/cc/7d/16a48e316e0b8e9a58edb887e6d332853695d19908c29224a8
    default:   Running setup.py bdist_wheel for httplib2: started
    default:   Running setup.py bdist_wheel for httplib2: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/ca/ac/5f/749651f7925b231103f5316cacca82a487810c22d30f011c0c
    default:   Running setup.py bdist_wheel for googleapis-common-protos: started
    default:   Running setup.py bdist_wheel for googleapis-common-protos: finished with status 'done'
    default:   Stored in directory: /root/.cache/pip/wheels/93/e0/cb/b06866f012310b96fba79c37f199aaf973a2e97a42ca7ef696
    default: Successfully built GoogleAppEngineCloudStorageClient httplib2 googleapis-common-protos
    default: Installing collected packages: iso8601, six, uritemplate, pyasn1, rsa, httplib2, pyasn1-modules, oauth2client, google-api-python-client, cachetools, google-auth, setuptools, protobuf, google-auth-httplib2, googleapis-common-protos, google-cloud-core, google-cloud-bigquery, beautifulsoup4, GoogleAppEngineCloudStorageClient
    default: Successfully installed GoogleAppEngineCloudStorageClient-1.9.22.1 beautifulsoup4-4.6.0 cachetools-2.0.1 google-api-python-client-1.6.2 google-auth-1.2.1 google-auth-httplib2-0.0.3 google-cloud-bigquery-0.25.0 google-cloud-core-0.25.0 googleapis-common-protos-1.5.3 httplib2-0.10.3 iso8601-0.1.11 oauth2client-4.1.2 protobuf-3.5.0.post1 pyasn1-0.4.2 pyasn1-modules-0.2.1 rsa-3.4.2 setuptools-38.2.0 six-1.11.0 uritemplate-3.0.0
    default: npm WARN prefer global
    default:  marked@0.3.6 should be installed with -g
    default: 
    default: > fsevents@1.1.3 install /tba/node_modules/fsevents
    default: > node install
    default: npm WARN
    default:  tba-gameday@0.0.0 No repository field.
    default: npm WARN tba-gameday@0.0.0 No license field.
    default: npm WARN The package babel-polyfill is included as both a dev and production dependency.
    default: npm WARN The package react-dom is included as both a dev and production dependency.
    default: npm WARN The package swagger-ui is included as both a dev and production dependency.
    default: added 1292 packages in 43.888s
    default: ---> pavement.make
    default: ---> pavement.javascript
    default: Combining and Compressing Javascript
    default: python do_compress.py js
    default: Compressing Main JavaScript...
    default: => static/compiled/javascript/tba_combined_js.main.min.js
    default: 
    default: Compressing Firebase Messaging Serviceworker JavaScript...
    default: => static/compiled/javascript/firebase-messaging-sw.js
    default: 
    default: Compressing GameDay JavaScript...
    default: => static/compiled/javascript/tba_combined_js.gameday.min.js
    default: 
    default: Compressing EventWizard JavaScript...
    default: => static/compiled/javascript/tba_combined_js.eventwizard.min.js
    default: ---> pavement.gulp
    default: Running 'gulp build'
    default: npm update && gulp build --production
    default: npm notice
    default:  save
    default:  swagger-ui is being moved from dependencies to devDependencies
    default: npm WARN
    default:  webpack-dev-middleware@1.12.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none was installed.
    default: npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.
    default: npm WARN worker-loader@0.7.1 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta but none was installed.
    default: npm WARN tba-gameday@0.0.0 No repository field.
    default: npm WARN tba-gameday@0.0.0 No license field.
    default: npm WARN The package babel-polyfill is included as both a dev and production dependency.
    default: npm WARN The package react-dom is included as both a dev and production dependency.
    default: added 1 package, removed 1 package and updated 3 packages in 17.512s
    default: [20:05:13] 
    default: Using gulpfile /tba/gulpfile.js
    default: [20:05:13] 
    default: Starting 'gameday-js'...
    default: [20:05:13] Finished 'gameday-js' after 20 ms
    default: [20:05:13] Starting 'gameday-less'...
    default: [20:05:13] Finished 'gameday-less' after 9.31 ms
    default: [20:05:13] Starting 'apidocs-js'...
    default: [20:05:13] Finished 'apidocs-js' after 3 ms
    default: [20:05:13] Starting 'apidocs-less'...
    default: [20:05:13] Finished 'apidocs-less' after 2.31 ms
    default: [20:05:13] Starting 'eventwizard-js'...
    default: [20:05:13] Finished 'eventwizard-js' after 4.47 ms
    default: [20:05:13] Starting 'eventwizard-less'...
    default: [20:05:13] Finished 'eventwizard-less' after 1.23 ms
    default: [20:05:13] Starting 'build'...
    default: [20:05:13] Finished 'build' after 106 μs
    default: [20:05:14] gulp-debug: react/gameday2/gameday2.css
    default: [20:05:14] 
    default: gulp-debug: 1 item
    default: [20:05:14] gulp-debug: react/apidocs/apidocs.css
    default: [20:05:14] gulp-debug: 1 item
    default: [20:05:14] 
    default: gulp-debug: react/eventwizard/eventwizard.css
    default: [20:05:14] 
    default: gulp-debug: 1 item
    default: [20:05:54] 
    default: gulp-debug: gameday2.min.js.map
    default: [20:05:54] gulp-debug: gameday2.min.js
    default: [20:05:54] gulp-debug: 2 items
    default: [20:06:29] gulp-debug: apidocs.min.js.map
    default: [20:06:29] 
    default: gulp-debug: apidocs.min.js
    default: [20:06:29] gulp-debug: 2 items
    default: [20:06:37] 
    default: gulp-debug: eventwizard.min.js.map
    default: [20:06:37] 
    default: gulp-debug: eventwizard.min.js
    default: [20:06:37] 
    default: gulp-debug: 2 items
    default: ---> pavement.less
    default: Building and Combining CSS
    default: lessc static/css/less_css/tba_style.main.less static/css/less_css/tba_style.main.css
    default: lessc static/css/less_css/tba_style.gameday.less static/css/less_css/tba_style.gameday.css
    default: python do_compress.py css
    default: Compressing Main CSS...
    default: => static/compiled/css/tba_combined_style.main.min.css
    default: 
    default: Compressing GameDay CSS...
    default: => static/compiled/css/tba_combined_style.gameday.min.css
    default: ---> pavement.jinja2
    default: python compile_jinja2_templates.py
    default: Compiling jinja2 templates to: templates_jinja2_compiled.zip
    default: Compilation complete!
    default: fatal: Not a git repository (or any of the parent directories): .git
==> default: Running provisioner: trigger...
==> default: Executing command "./ops/dev/pull-datastore.sh push"...
==> default: Found running container to push datastore
==> default: Updating ssh known hosts...
==> default: Host 127.0.0.1 not found in /Users/gregmarra/.ssh/known_hosts
==> default: Command execution finished.
==> default: Running provisioner: shell...
    default: Running: inline script
    default: no server running on /tmp/tmux-0/default
    default: Starting devserver in new tmux session...
    default: tba: 3 windows (created Sun Nov 26 20:06:43 2017) [80x23]
    default: 0: bash* (1 panes) [80x23] [layout ae5d,80x23,0,0,0] @0 (active)
    default: 1: gae (1 panes) [80x23] [layout ae5e,80x23,0,0,1] @1
    default: 2: gulp- (1 panes) [80x23] [layout ae5f,80x23,0,0,2] @2
==> default: Running cleanup tasks for 'trigger' provisioner...
```

Then in the docker

`paver bootstrap` =>
```
root@tba-docker:/tba# paver bootstrap
---> pavement.bootstrap
Running python bootstrap.py --url localhost:41017 2016necmp
Configuring GAE Remote API on localhost:41017 to import 2016necmp
Traceback (most recent call last):
  File "bootstrap.py", line 247, in <module>
    main(args.key, args.url)
  File "bootstrap.py", line 214, in main
    remote_api_stub.ConfigureRemoteApi(None, '/_ah/remote_api', local_auth_func, url)
  File "/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 881, in ConfigureRemoteApi
    app_id = GetRemoteAppIdFromServer(server, path, rtok)
  File "/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 586, in GetRemoteAppIdFromServer
    response = server.Send(path, payload=None, **urlargs)
  File "/google_appengine/google/appengine/tools/appengine_rpc.py", line 393, in Send
    f = self.opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 99] Cannot assign requested address>
```

**Comment by bdaroz** [comment]
That almost looks like a docker networking error.

**Comment by phil-lopreiato** [comment]
Port 41017 is a default value that's unlikely to actually be in use (I should remove it). @gregmarra - can you see if `/var/log/tba.log` exists in the container?

**Comment by bdaroz** [comment]
The error can also be thrown if the container cannot assign an IP to source the traffic from. Make sure the container has access to the `localhost` IP address.

**Comment by gregmarra** [comment]
@phil-lopreiato no log

```
root@tba-docker:/tba# ls -l /var/log/
total 332
-rw-r--r-- 1 root root  13267 Nov 19 04:26 alternatives.log
drwxr-xr-x 1 root root   4096 Nov 19 04:26 apt
-rw-r--r-- 1 root root  42621 Nov 14 13:48 bootstrap.log
-rw-rw---- 1 root utmp      0 Nov 14 13:48 btmp
-rw-r----- 1 root adm      31 Nov 14 13:48 dmesg
-rw-r--r-- 1 root root 224339 Nov 19 04:26 dpkg.log
-rw-r--r-- 1 root root   3392 Nov 19 04:26 faillog
drwxr-xr-x 2 root root   4096 Nov 14 13:48 fsck
-rw-rw-r-- 1 root utmp  30952 Nov 26 20:09 lastlog
-rw-rw-r-- 1 root utmp   1536 Nov 26 20:09 wtmp
```

**Comment by phil-lopreiato** [comment]
Okay, that's your problem. Make sure you repo is past 2a42c6df129cecb290ba1a60f909dd2467563fe3, then make sure everything is synced to the container. I'd run `vagrant rsync; vagrant halt; vagrant up` to make sure you start the devserver with the changes reflected.

**Comment by gregmarra** [comment]
New error!

```
root@tba-docker:/tba# paver bootstrap
---> pavement.bootstrap


Captured Task Output:
---------------------

---> pavement.bootstrap
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paver/tasks.py", line 190, in _run_task
    return do_task()
  File "/usr/local/lib/python2.7/dist-packages/paver/tasks.py", line 187, in do_task
    return func(**kw)
  File "pavement.py", line 183, in bootstrap
    if not options.bootstrap.port:
  File "/usr/local/lib/python2.7/dist-packages/paver/options.py", line 23, in __getattr__
    raise AttributeError(name)
AttributeError: port
```

**Comment by phil-lopreiato** [comment]
d'oh. Okay, I think I've fixed the clownyness.

**Comment by bdaroz** [comment]
Given we've had several updates and other people getting working paver bootstraps working, and the age of the issue I'm going to close. Please reopen if still a problem.
