### ISSUE TITLE
Unicode in Award Names

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#636]
I think it's only in the Gracious Professionalism awards for 2013 - it's not a huge deal, but it was an annoying edge-case when I was trying to grab some data

Link: http://www.thebluealliance.com/team/2337#2013mibed

**Comment by fangeugene** [comment]
Fixed in #910

**Comment by fangeugene** [comment]
Ok I manually fixed that. This shouldn't be an issue in the future since we are no longer scraping HTML pages.

**Comment by tsteward** [comment]
It doesn't look fixed to me. I still see bad characters in all of the gracious professionalism awards for 2013.

**Comment by fangeugene** [comment]
Oh I thought it was just that one event. I'll fix all of 2013.

**Comment by tsteward** [comment]
It's also a problem in 2014 events.

**Comment by fangeugene** [comment]
Both should be fixed aside from cached pages.
